apiVersion: v2
name: srm
description: Helm chart for Harness SRM
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - condition: global.ng.enabled
    name: cv-nextgen
    repository: https://harness.github.io/services/placeholder
    version: 0.3.x
  - condition: global.ng.enabled
    name: le-nextgen
    repository: https://harness.github.io/services/placeholder
    version: 0.3.x
  - condition: global.cg.enabled
    name: learning-engine
    repository: https://harness.github.io/services/placeholder
    version: 0.4.x
  - name: verification-svc
    condition: global.cg.enabled
    version: 0.4.x
    repository: https://harness.github.io/services/placeholder