apiVersion: v2
name: cd
description: Helm chart for Harness CD
type: application
version: 0.8.0
appVersion: "1.16.0"
dependencies:
  - condition: global.gitops.enabled
    name: gitops
    repository: https://harness.github.io/services/placeholder
    version: 0.8.x