apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverse-proxy
  template:
    metadata:
      labels:
        app: reverse-proxy
    spec:
      containers:
        - name: reverse-proxy
          image: harness/reverse-proxy
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: reverse-proxy
spec:
  type: ClusterIP
  selector:
    app: reverse-proxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
