## Global Settings
global:
  # -- Enable for complete airgap environment
  airgap: false
  ha: true
  # -- Global Docker image registry
  imageRegistry: ""
  # -- Fully qualified URL of your loadbalancer (ex: https://www.foo.com)
  loadbalancerURL: ""
  mongoSSL: false
  storageClassName: ""
  ingress:
    useSelfSignedCert: false
  # -- Enable to install CD
  cd:
    enabled: false
  # -- Enable to install CI
  ci:
    enabled: false
  # -- Enable to install STO
  sto:
    enabled: false

  # -- Enable to install SRM
  srm:
    enabled: false
  # -- Enable to install FF
  ff:
    enabled: false
  # -- Enable to install CDB
  ngcustomdashboard:
    enabled: false
  # -- Enable to install CCM
  ccm:
    enabled: true

