postgresql:
  fullnameOverride: "postgres"
  auth:
    # Create the additional ET Database during deployment.
    # Additional init can be added using a configmap
    # primary.initdb.scriptsConfigMap
    database: overops
    existingSecret: "postgres"
  commonLabels:
    app: postgres
  image:
    tag: "14.8.0-debian-11-r17"
