apiVersion: v2
name: ci
description: A Helm chart for Kubernetes
type: application
version: 0.5.0
appVersion: "1.16.0"
dependencies:
  - name: ci-manager
    version: 0.6.x
    repository: "https://harness.github.io/services/placeholder"
