apiVersion: v2
appVersion: 1.16.0
dependencies:
  - name: ci-manager
    repository: https://harness.github.io/services/placeholder
    version: 0.5.x
  - condition: global.ng.enabled
    name: ti-service
    repository: https://harness.github.io/services/placeholder
    version: 0.3.x
description: A Helm chart for Kubernetes
name: ci
type: application
version: 0.5.0
