## Global Settings
global:
  # -- Enable for complete airgap environment
  airgap: false
  ha: true
  # -- Global Docker image registry
  imageRegistry: ""
  # -- Fully qualified URL of your loadbalancer (ex: https://www.foo.com)
  loadbalancerURL: ""
  mongoSSL: false
  storageClassName: ""

  sto:
    # -- Enable to install STO
    enabled: false

  et:
    # -- Enable to install Error Tracking
    enabled: false

  ngcustomdashboard:
    # --  Enabled Custom Dashboard
    enabled: true

  istio:
    enabled: false
    gateway:
      # -- Enable to create istio-system gateway
      create: true
      port: 443
      protocol: HTTPS
    hosts:
      - '*'
    tls:
      credentialName:
      minProtocolVersion: TLSV1_2
      mode: SIMPLE
    virtualService:
      gateways:
        - ""
      hosts:
        - ""

  ingress:
    enabled: false
    createNginxIngressController: false
    createDefaultBackend: false
    loadBalancerIP: '0.0.0.0'
    className: "harness"
    loadBalancerEnabled: false
    useSelfSignedCert: false
    nginx:
      image:
        registry:  us.gcr.io
        repository: k8s-artifacts-prod/ingress-nginx/controller
        pullPolicy: IfNotPresent
        # Overrides the image tag whose default is the chart appVersion.
        tag: "v1.0.0-alpha.2"
        digest: ""
    defaultbackend:
      image:
        registry: k8s.gcr.io
        repository: defaultbackend-amd64
        pullPolicy: IfNotPresent
        # Overrides the image tag whose default is the chart appVersion.
        tag: "1.5"
        digest: ""
    hosts:
      - 'my-host.example.org'
    tls:
      enabled: false
      secretName: harness-ssl

## Platform Settings
harness:
  platform:
    # -- Feature list to enable within platform.  Contact Harness for value
    access-control:
      autoscaling:
        enabled: false
      replicaCount: 1
      appLogLevel: INFO
      java:
        memory: 512m
      resources:
        limits:
          cpu: 1
          memory: 4096Mi
        requests:
          cpu: 1
          memory: 4096Mi

    change-data-capture:
      appLogLevel: INFO
      java:
        memory: 2048
      resources:
        limits:
          cpu: 1
          memory: 2880Mi
        requests:
          cpu: 1
          memory: 2880Mi
      autoscaling:
        enabled: false
      replicaCount: 1

    cv-nextgen:
      java:
        memory: 1024
      resources:
        limits:
          cpu: 0.5
          memory: 1440Mi
        requests:
          cpu: 0.5
          memory: 1440Mi
      autoscaling:
        enabled: false
      replicaCount: 1

    delegate-proxy:
      resources:
        limits:
          cpu: 200m
          memory: 100Mi
        requests:
          cpu: 200m
          memory: 100Mi
      autoscaling:
        enabled: false
      replicaCount: 1

    gateway:
      java:
        memory: 1024
      resources:
        limits:
          cpu: 0.5
          memory: 1300Mi
        requests:
          cpu: 0.2
          memory: 1300Mi
      autoscaling:
        enabled: false
      replicaCount: 1

    harness-manager:
      external_graphql_rate_limit: "500"
      autoscaling:
        enabled: false
      replicaCount: 1
      java:
        memory: "2048"
      resources:
        limits:
          cpu: 0.5
          memory: 3000Mi
        requests:
          cpu: 0.5
          memory: 3000Mi

    le-nextgen:
      autoscaling:
        enabled: false
      replicaCount: 1
      resources:
        limits:
          cpu: 0.5
          memory: 512Mi
        requests:
          cpu: 0.5
          memory: 512Mi

    log-service:
      autoscaling:
        enabled: false
      replicaCount: 1
      resources:
        limits:
          cpu: 0.5
          memory: 1400Mi
        requests:
          cpu: 0.5
          memory: 1400Mi
    minio:
      fullnameOverride: "minio"
      mode: standalone
      defaultBuckets: "logs"
      persistence:
        size: 10Gi

    mongodb:
      replicaCount: 1
      resources:
        limits:
          cpu: 2
          memory: 2048Mi
        requests:
          cpu: 1
          memory: 2048Mi
      persistence:
        size: 20Gi
      args:
        - "--wiredTigerCacheSizeGB=0.5"

    next-gen-ui:
      autoscaling:
        enabled: false
      replicaCount: 1
      resources:
        limits:
          cpu: 0.2
          memory: 200Mi
        requests:
          cpu: 0.2
          memory: 200Mi

    ng-auth-ui:
      autoscaling:
        enabled: false
      replicaCount: 1
      resources:
        limits:
          cpu: 0.2
          memory: 200Mi
        requests:
          cpu: 0.2
          memory: 200Mi

    ng-manager:
      autoscaling:
        enabled: false
      replicaCount: 1
      java:
        memory: "4096m"
      resources:
        limits:
          cpu: 0.5
          memory: 6144Mi
        requests:
          cpu: 0.5
          memory: 6144Mi

    pipeline-service:
      autoscaling:
        enabled: false
      replicaCount: 1
      java:
        memory: "1024m"
      resources:
        limits:
          cpu: 0.5
          memory: 1400Mi
        requests:
          cpu: 0.5
          memory: 1400Mi

    platform-service:
      autoscaling:
        enabled: false
      replicaCount: 1
      java:
        memory: "2048m"
      resources:
        limits:
          cpu: 0.5
          memory: 3000Mi
        requests:
          cpu: 0.5
          memory: 3000Mi

    redis:
      useAntiAffinity: false
      redis:
        resources:
          limits:
            cpu: 1
            memory: 2048Mi
          requests:
            cpu: 1
            memory: 2048Mi
      replicaCount: 3
      sentinel:
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
      volumeClaimTemplate:
        resources:
          requests:
            storage: 10Gi

    scm-service:
      autoscaling:
        enabled: false
      replicaCount: 1
      resources:
        limits:
          cpu: 0.1
          memory: 512Mi
        requests:
          cpu: 0.1
          memory: 512Mi

    template-service:
      autoscaling:
        enabled: false
      replicaCount: 1
      java:
        memory: "1024m"
      resources:
        limits:
          cpu: 0.5
          memory: 1500Mi
        requests:
          cpu: 0.5
          memory: 1500Mi

    ti-service:
      autoscaling:
        enabled: false
      replicaCount: 1
      jobresources:
        limits:
          cpu: 0.5
          memory: 1400Mi
        requests:
          cpu: 0.5
          memory: 1400Mi
      resources:
        limits:
          cpu: 0.5
          memory: 1400Mi
        requests:
          cpu: 0.5
          memory: 1400Mi

    timescaledb:
      autoscaling:
        enabled: false
      replicaCount: 1
      resources:
        limits:
          cpu: 0.3
          memory: 512Mi
        requests:
          cpu: 0.3
          memory: 512Mi
      storage:
        capacity: 10Gi

  ci:
  # -- Enable to install CI
    enabled: true
    ci-manager:
      autoscaling:
        enabled: false
      replicaCount: 1
      java:
        memory: "2048m"
      resources:
        limits:
          cpu: 0.5
          memory: 3000Mi
        requests:
          cpu: 0.5
          memory: 3000Mi

  sto:
    sto-core:
      autoscaling:
        enabled: false
      replicaCount: 1
      resources:
        limits:
          cpu: 500m
          memory: 500Mi
        requests:
          cpu: 500m
          memory: 500Mi
    sto-manager:
      autoscaling:
        enabled: false
      replicaCount: 1
      resources:
        limits:
          cpu: 1
          memory: 3072Mi
        requests:
          cpu: 1
          memory: 3072Mi

  et:
    enable-receivers: false
    et-service:
      et:
        java:
          heapSize: "2048m"
        redis:
          enabled: false
      autoscaling:
        enabled: false
      replicaCount: 1
      resources:
        limits:
          cpu: 1
          memory: 3Gi
        requests:
          cpu: 100m
          memory: 3Gi
    et-collector:
      et:
        java:
          heapSize: "1600m"
      autoscaling:
        enabled: false
      replicaCount: 1
      resources:
        limits:
          cpu: 500m
          memory: 2Gi
        requests:
          cpu: 100m
          memory: 2Gi
