global:
  airgap: "false"
  ha: false
  host_name: ""
  imageRegistryOverride: ""
  loadbalancerURL: ""
  mongoSSL: false
  storageClassName: ""

ci:
  enabled: true

sto:
  enabled: true

istio:
  enabled: true
  gateway:
    create: true
    port: 443
    protocol: HTTPS
  hosts:
    - '*'
  tls:
    credentialName:
    minProtocolVersion: TLSV1_2
    mode: SIMPLE
  virtualService:
    gateways:
      - ""
    hosts:
      - ""

