apiVersion: v2
appVersion: 1.16.0
dependencies:
- name: policy-mgmt
  repository: https://harness.github.io/services/placeholder
  version: 0.8.x
description: A Helm chart for Harness policy management
name: opa
type: application
version: 0.6.0
