apiVersion: v2
appVersion: 1.16.1
dependencies:
- condition: global.ng.enabled
  name: access-control
  repository: https://harness.github.io/services/placeholder
  version: x.x.x
- condition: global.ng.enabled
  name: change-data-capture
  repository: https://harness.github.io/services/placeholder
  version: x.x.x
- condition: global.ng.enabled
  name: cv-nextgen
  repository: https://harness.github.io/services/placeholder
  version: x.x.x
- name: gateway
  repository: https://harness.github.io/services/placeholder
  version: x.x.x
- name: harness-manager
  repository: https://harness.github.io/services/placeholder
  version: x.x.x
- name: delegate-proxy
  repository: https://harness.github.io/services/placeholder
  version: x.x.x
- condition: global.ng.enabled
  name: le-nextgen
  repository: https://harness.github.io/services/placeholder
  version: x.x.x
- condition: global.cg.enabled
  name: learning-engine
  repository: https://harness.github.io/services/placeholder
  version: x.x.x
- condition: global.ng.enabled
  name: log-service
  repository: https://harness.github.io/services/placeholder
  version: x.x.x
- condition: global.migrator.enabled
  name: migrator
  repository: https://harness.github.io/services/placeholder
  version: x.x.x
- condition: global.ng.enabled
  name: next-gen-ui
  repository: https://harness.github.io/services/placeholder
  version: x.x.x
- name: ng-auth-ui
  repository: https://harness.github.io/services/placeholder
  version: x.x.x
- condition: global.ng.enabled
  name: ng-manager
  repository: https://harness.github.io/services/placeholder
  version: x.x.x
- condition: global.ng.enabled
  name: pipeline-service
  repository: https://harness.github.io/services/placeholder
  version: x.x.x
- condition: global.ng.enabled
  name: platform-service
  repository: https://harness.github.io/services/placeholder
  version: x.x.x
- condition: global.ng.enabled
  name: scm-service
  repository: https://harness.github.io/services/placeholder
  version: x.x.x
- condition: global.ng.enabled
  name: template-service
  repository: https://harness.github.io/services/placeholder
  version: x.x.x
- condition: global.ng.enabled
  name: ti-service
  repository: https://harness.github.io/services/placeholder
  version: x.x.x
- condition: global.cg.enabled
  name: ui
  repository: https://harness.github.io/services/placeholder
  version: x.x.x
- condition: global.cg.enabled
  name: verification-svc
  repository: https://harness.github.io/services/placeholder
  version: x.x.x
- condition: global.bootstrap.enabled
  name: bootstrap
  repository: https://harness.github.io/services/placeholder
  version: x.x.x
description: Helm chart for Harness Platform
name: platform
type: application
version: 0.8.15
