apiVersion: batch/v1          ## The version of the Kubernetes API
kind: Job                     ## The type of object for jobs
metadata:
 name: image-pull-secrets
 namespace: {{.Values.namespace}}
spec:                         ## What state you desire for the object
 template:
   metadata:
     name: image-pull-secrets
   spec:
     containers:
     - name: job
       image: alpine:latest                  ##  Image used
       command: ["echo", "hello"] 
     restartPolicy: Never          ##  Restart Policy in case container failed
